# https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md
# Start with defaults.
default: true
# MD013/line-length - Line length
MD013:
  # Number of characters
  line_length: 120
# MD030/list-marker-space - Spaces after list markers
MD030:
  # Spaces for single-line unordered list items
  ul_single: 1
  # Spaces for single-line ordered list items
  ol_single: 2
  # Spaces for multi-line unordered list items
  ul_multi: 1
  # Spaces for multi-line ordered list items
  ol_multi: 2
MD033:
  allowed_elements:
    - a
    - img
