# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-vcs-permalinks
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: local
  hooks:
  - id: no-draft-posts
    name: Check for `draft = true`
    description: >-
      Hugo does not publish draft posts, prevent draft posts being committed
    language: pygrep
    types: [markdown]
    entry: ^draft.*=.*true
