#!/bin/bash
# When tags are inconsistently capitalised Hugo will use a random tag, causing
# unnecessary changes in output.  Prevent checking in inconsistent tags.

set -e -f -u -o pipefail

main() {
  local bad_tags
  bad_tags="$(make --quiet tags_list \
                | awk '{print tolower($2)}' \
                | sort \
                | uniq -d)"
  if [[ -z "${bad_tags}" ]]; then
    return 0
  fi
  printf "Inconsistent tag capitalisation found: %s\\n" "${bad_tags}"
  return 1
}

main "$@"
