baseURL = "https://www.johntobin.ie/"
languageCode = "en-us"
title = "John Tobin"
theme = "hugo-coder"
googleAnalytics = 'G-MYL6PFZFFX'
pygmentsCodefences = true
pygmentsStyle = "solarized-dark"
newContentEditor = "nvim"
enableGitInfo = true

[params]
  author = 'John Tobin'
  info = 'Slowly Reducing Entropy'
  description = 'John Tobin description'
  keywords = 'blog,personal,SRE,sysadmin,developer,manager'
  hidecredits = true
  hidecopyright = true
  # /site.webmanifest doesn't exist; point this towards something that exists
  # so that probers don't encounter errors.
  manifest = '/index.html'
  # Similarly /images/safari-pinned-tab.svg doesn't exist.
  mask_icon = '/index.html'

[pagination]
  pagerSize = 50

[frontmatter]
  # Automatically work out the date to use from git; allow it to be overridden
  # with `lastmod` in the file, and fall back to `date` in the file (probably
  # only necessary when writing a post).
  date = ['lastmod', ':git', 'date', 'publishDate']

[[menu.main]]
  name = 'About me'
  weight = 1
  url = '/about/'

[[menu.main]]
  name = 'Blog'
  weight = 2
  url = '/blog/'

[[menu.main]]
  name = 'Publications'
  weight = 3
  url = '/publications/'

[security]
  [security.exec]
    allow = ['^nvim$', '^dart-sass-embedded$', '^git$', '^go$', '^npx$', '^postcss$']
    # By default most environment variables are removed before starting the
    # editor, causing vim to not read ~/.vimrc, $PATH is bad, and probably more.
    # Keep all environment variables because I run vim with those environment
    # variables set all the time.
    osEnv = ['.*']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # Include inline HTML rather than stripping it.
      unsafe = true
