baseURL = "https://www.johntobin.ie/"
languageCode = "en-us"
title = "John Tobin"
theme = "hugo-coder"
googleAnalytics = 'UA-18492319-1'

[params]
  author = 'John Tobin'
  info = 'Slowly Reducing Entropy'
  description = 'John Tobin description'
  keywords = 'blog,personal,SRE,sysadmin,developer,manager'
  hidecredits = true
  hidecopyright = true

[[menu.main]]
  name = 'Blog'
  weight = 1
  url = '/blog/'

[[menu.main]]
  name = 'Publications'
  weight = 1
  url = '/publications/'
