#!/bin/bash

set -e -u -o pipefail

markdown_files_being_committed() {
  git diff --cached --name-only --diff-filter=ACM \
    | (grep ^content/blog || true)
}

# When tags are inconsistently capitalised Hugo will use a random tag, causing
# unnecessary changes in output.  Prevent checking in inconsistent tags.
check_for_inconsistent_tags() {
  local bad_tags
  bad_tags="$(make --quiet tags_list \
                | awk '{print tolower($2)}' \
                | sort \
                | uniq -d)"
  if [[ -z "${bad_tags}" ]]; then
    return 0
  fi
  printf "Inconsistent tag capitalisation found: %s\\n" "${bad_tags}"
  return 1
}

main() {
  local exit_status=0

  if ! check_for_inconsistent_tags; then
    exit_status=1
  fi

  exit "${exit_status}"
}

main
