#!/bin/bash

set -e -u -o pipefail

status=0
for file in $(git diff --cached --name-only --diff-filter=ACM \
                | grep content/blog); do
  if grep -H --color=auto '^draft.*=.*true' "${file}"; then
    status=1
  fi
done
if [[ "${status}" == 1 ]]; then
  printf "draft entries found\\n" >&2
fi
exit "${status}"
