#!/bin/bash

set -e -u -o pipefail

markdown_files_being_committed() {
  git diff --cached --name-only --diff-filter=ACM \
    | (grep ^content/blog || true)
}

check_for_drafts() {
  local drafts_found=0 file
  for file in $(markdown_files_being_committed); do
    if grep -H --color=auto '^draft.*=.*true' "${file}"; then
      drafts_found=1
    fi
  done
  return "${drafts_found}"
}

main() {
  local exit_status=0

  if ! check_for_drafts; then
    printf "draft entries found\\n" >&2
    exit_status=1
  fi

  exit "${exit_status}"
}

main
